# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
appVersion: "1.0"
description: A Helm chart for the Gardener Networking Policy Filter Extension for Shoots.
name: gardener-extension-networking-policy-filter
version: 0.1.0
