# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: extension-shoot-networking-filter.config
  namespace: {{ .Release.Namespace }}	
data:
  config.yaml: |
    apiVersion: shoot-networking-filter.extensions.config.gardener.cloud/v1alpha1
    kind: Configuration
{{- if .Values.egressFilter }}
    egressFilter:
{{ toYaml .Values.egressFilter | trim | indent 6 }}
{{- end}}